import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { build } from 'esbuild';
import { getIntrospectionQuery } from 'graphql';

const here = dirname(fileURLToPath(import.meta.url));

// The introspection query the client sends is graphql-js's own, with the same
// options a standard code generator uses. `inputValueDeprecation` stays off:
// the spec records that Koine's library serves __InputValue.isDeprecated as
// null against a non-null declaration, so selecting it would fail there.
const introspectionQuery = getIntrospectionQuery({ descriptions: true });

const capture = JSON.parse(await readFile(join(here, 'capture/capture.json'), 'utf8'));

await mkdir(join(here, 'src/generated'), { recursive: true });
await writeFile(
  join(here, 'src/generated/contract.ts'),
  `// Generated by build.mjs. Do not edit.\n` +
    `export const INTROSPECTION_QUERY = ${JSON.stringify(introspectionQuery)};\n` +
    `export const GENERATED_AGAINST_SCHEMA_DIGEST = ${JSON.stringify(capture.schemaDigest)};\n` +
    `export const GENERATED_AGAINST_CONTRACT_VERSION = ${JSON.stringify(capture.contractVersion)};\n`,
  'utf8',
);

const result = await build({
  entryPoints: [join(here, 'src/cli.ts')],
  bundle: true,
  platform: 'node',
  target: 'node24',
  format: 'esm',
  outfile: join(here, 'dist/koine-client.mjs'),
  banner: { js: '#!/usr/bin/env node' },
  legalComments: 'none',
  metafile: true,
});

const external = Object.keys(result.metafile.inputs).filter((p) => p.includes('node_modules'));
if (external.length > 0) {
  throw new Error(`bundle pulled in node_modules: ${external.join(', ')}`);
}
console.log('built dist/koine-client.mjs');
